// Reads `forge build` artifacts from ../out/ and writes the bytecode +
// ABI into src/bytecode.ts and src/abis.ts. Run `forge build` in the
// `contracts/` parent directory before invoking this script.

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const contractsRoot = resolve(__dirname, "../..");

function loadArtifact(relPath: string): { bytecode: string; abi: unknown } {
  const full = resolve(contractsRoot, relPath);
  if (!existsSync(full)) {
    console.error(`Missing forge artifact: ${full}`);
    console.error(
      `Run \`forge build\` in ${contractsRoot} first, then re-run this script.`,
    );
    process.exit(1);
  }
  const json = JSON.parse(readFileSync(full, "utf8"));
  const bytecode: string = json.bytecode?.object ?? "";
  if (!bytecode || !bytecode.startsWith("0x") || bytecode.length < 10) {
    console.error(`Artifact ${relPath} has no usable bytecode`);
    process.exit(1);
  }
  return { bytecode, abi: json.abi };
}

const bridge = loadArtifact("out/HypersnapBridge.sol/HypersnapBridge.json");
const proxy = loadArtifact("out/ERC1967Proxy.sol/ERC1967Proxy.json");

const bytecodeOut = `// AUTO-GENERATED by scripts/generate-bytecode.ts. Do not edit by hand.
// Regenerate after \`forge build\` in ../ — npm scripts predev/prebuild do this.

export const BRIDGE_BYTECODE = "${bridge.bytecode}" as const;
export const PROXY_BYTECODE = "${proxy.bytecode}" as const;
`;
writeFileSync(resolve(__dirname, "../src/bytecode.ts"), bytecodeOut);

const abisOut = `// AUTO-GENERATED by scripts/generate-bytecode.ts. Do not edit by hand.

export const BRIDGE_ABI = ${JSON.stringify(bridge.abi, null, 2)} as const;
export const PROXY_ABI = ${JSON.stringify(proxy.abi, null, 2)} as const;
`;
writeFileSync(resolve(__dirname, "../src/abis.ts"), abisOut);

console.log("Wrote src/bytecode.ts and src/abis.ts");
