// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.24;

import {Test} from "forge-std/Test.sol";
import {HypersnapBridge} from "../src/HypersnapBridge.sol";

/// @title Cross-side digest test vectors.
/// @notice The hex values pinned in this file MUST match the values produced
/// by the Rust encoder in `crates/hypersnap-crypto/src/bridge_payload.rs`.
/// Any change to a domain tag, encoding layout, or field width on either
/// side must update both files in lockstep — and any drift will cause one
/// (likely both) to fail.
///
/// Vectors were generated by running:
///   `cargo run -p hypersnap-bridge-ceremony -- digest <subcommand> ...`
/// with the exact arguments shown in each test below.
contract CrossSideDigestsTest is Test {
    bytes32 constant DOMAIN_MERKLE_ROOT_UPDATE = keccak256("HYPERSNAP_MERKLE_ROOT_UPDATE_V1");
    bytes32 constant DOMAIN_OWNER_UPDATE       = keccak256("HYPERSNAP_OWNER_UPDATE_V1");
    bytes32 constant DOMAIN_OWNER_ACCEPTANCE   = keccak256("HYPERSNAP_OWNER_ACCEPTANCE_V1");
    bytes32 constant DOMAIN_UPGRADE            = keccak256("HYPERSNAP_UPGRADE_V1");
    bytes32 constant DOMAIN_UPGRADE_CANCEL     = keccak256("HYPERSNAP_UPGRADE_CANCEL_V1");
    bytes32 constant DOMAIN_PAUSE              = keccak256("HYPERSNAP_PAUSE_V1");
    bytes32 constant DOMAIN_RECOVER_ERC20      = keccak256("HYPERSNAP_RECOVER_ERC20_V1");
    bytes32 constant DOMAIN_LOCK_LEAF          = keccak256("HYPERSNAP_LOCK_LEAF_V1");

    uint8 constant FAMILY_EVM = 0;

    // Test addresses (EIP-55 checksummed). The byte values match the Rust
    // tests verbatim — Solidity's lexer requires checksumming on hex literals
    // of address-length, but the underlying 20 bytes are the raw values.
    address constant ADDR_OWNER_A     = 0x0102030405060708090a0B0c0d0e0f1011121314;
    address constant ADDR_NEW_OWNER_B = 0xAAbbCCDdeEFf00112233445566778899aABBcCDd;
    address constant ADDR_IMPL        = 0xA0B0c0d0e0f000102030405060708090A0B0C0D0;
    address constant ADDR_TOKEN       = 0xa0b1c2d3E4f5a6b7C8d9e0F1a2b3c4d5e6F70809;

    // -----------------------------------------------------------------------
    // Universal signed payloads
    // -----------------------------------------------------------------------

    /// `digest root-update --root 0x1122...eeff --block 0x0123456789abcdef`
    function test_rootUpdateDigest_pinned() public pure {
        bytes32 root = 0x11223344556677889900aabbccddeeff11223344556677889900aabbccddeeff;
        uint64 blockNumber = 0x0123456789abcdef;

        bytes32 digest = keccak256(abi.encodePacked(
            DOMAIN_MERKLE_ROOT_UPDATE,
            bytes8(blockNumber),
            root
        ));

        assertEq(
            digest,
            0xeaa5a98d4834102782c865c6a2876889d10f833e09a9f9ac3efe444f1b45ef43
        );
    }

    /// `digest rotate-auth --new-owner 0x0102...1314 --block 42`
    function test_ownerUpdateDigest_pinned() public pure {
        uint64 blockNumber = 42;

        bytes32 digest = keccak256(abi.encodePacked(
            DOMAIN_OWNER_UPDATE,
            bytes8(blockNumber),
            bytes20(ADDR_OWNER_A)
        ));

        assertEq(
            digest,
            0x5d3035ddc3511b360e59df51cf7666089b9a39dd28687ceb53b4fb81c99fce56
        );
    }

    /// `digest owner-acceptance --new-owner 0xaabb...ccdd`
    function test_ownerAcceptanceDigest_pinned() public pure {
        bytes32 digest = keccak256(abi.encodePacked(
            DOMAIN_OWNER_ACCEPTANCE,
            bytes20(ADDR_NEW_OWNER_B)
        ));

        assertEq(
            digest,
            0x3f1488f474e6477ff283e815202bf6aa5a64c47461f7258de5dd4c3ae0b41b6c
        );
    }

    /// `digest upgrade-propose --new-implementation 0xa0b0...c0d0 --block 7`
    function test_upgradeDigest_pinned() public pure {
        uint64 blockNumber = 7;

        bytes32 digest = keccak256(abi.encodePacked(
            DOMAIN_UPGRADE,
            bytes8(blockNumber),
            bytes20(ADDR_IMPL)
        ));

        assertEq(
            digest,
            0x8fbd2cd60bfdf32c16dbfe102f6962900cb45cfc6625a01f030d94a050d0aa69
        );
    }

    /// `digest upgrade-cancel --pending-implementation 0xa0b0...c0d0 --block 11`
    function test_upgradeCancelDigest_pinned() public pure {
        uint64 blockNumber = 11;

        bytes32 digest = keccak256(abi.encodePacked(
            DOMAIN_UPGRADE_CANCEL,
            bytes8(blockNumber),
            bytes20(ADDR_IMPL)
        ));

        assertEq(
            digest,
            0x631f9827e00b8b52c28f3b54cc6565b13404e6167d87d2d6f2400dd9b790183e
        );
    }

    /// `digest pause --block 99`
    function test_pauseDigest_pinned() public pure {
        uint64 blockNumber = 99;

        bytes32 digest = keccak256(abi.encodePacked(
            DOMAIN_PAUSE,
            bytes8(blockNumber)
        ));

        assertEq(
            digest,
            0xaa5b0e0a36fc32fc7c8692dcaa03d7555a0ed15521414e610d51e60362cec9b6
        );
    }

    // -----------------------------------------------------------------------
    // Chain-specific signed payload
    // -----------------------------------------------------------------------

    /// `digest recover-erc20 --chain-id 1 --block 5 --token 0xa0b1...0809
    ///                       --to 0x0102...1314 --amount 100`
    function test_recoverErc20Digest_pinned() public pure {
        uint256 chainId = 1;
        uint64 blockNumber = 5;
        uint256 amount = 100;

        bytes32 digest = keccak256(abi.encodePacked(
            DOMAIN_RECOVER_ERC20,
            bytes32(chainId),
            bytes8(blockNumber),
            bytes20(ADDR_TOKEN),
            bytes20(ADDR_OWNER_A),
            bytes32(amount)
        ));

        assertEq(
            digest,
            0x2201113fe69e2b4fc09cf4c63d94e8ab6c084ae628ad4d1929ec9693bbfe1e18
        );
    }

    // -----------------------------------------------------------------------
    // Lock leaf encoding
    // -----------------------------------------------------------------------

    /// `digest lock-leaf-evm --lock-id 0xdead...7788 --destination-chain-id 1
    ///                        --recipient 0x0102...1314 --amount 1000000`
    function test_lockLeafEvm_pinned() public pure {
        bytes32 lockId = 0xdeadbeefcafebabe1122334455667788deadbeefcafebabe1122334455667788;
        uint32 destinationChainId = 1;
        uint256 amount = 1_000_000;

        bytes32 leaf = keccak256(abi.encodePacked(
            DOMAIN_LOCK_LEAF,
            lockId,
            bytes1(FAMILY_EVM),
            bytes4(destinationChainId),
            bytes20(ADDR_OWNER_A),
            bytes32(amount)
        ));

        assertEq(
            leaf,
            0x946e398b9ac10b77850cfc5877dab9207e37c8622db8bbacecbbc1c997818996
        );
    }

    // -----------------------------------------------------------------------
    // Domain tags (sanity)
    // -----------------------------------------------------------------------

    /// All eight domain-tag hashes must be pairwise distinct.
    function test_domainTags_pairwiseDistinct() public pure {
        bytes32[8] memory tags = [
            DOMAIN_MERKLE_ROOT_UPDATE,
            DOMAIN_OWNER_UPDATE,
            DOMAIN_OWNER_ACCEPTANCE,
            DOMAIN_UPGRADE,
            DOMAIN_UPGRADE_CANCEL,
            DOMAIN_PAUSE,
            DOMAIN_RECOVER_ERC20,
            DOMAIN_LOCK_LEAF
        ];
        for (uint256 i = 0; i < tags.length; i++) {
            for (uint256 j = i + 1; j < tags.length; j++) {
                assertTrue(tags[i] != tags[j], "domain tag collision");
            }
        }
    }

    /// The constants declared in this test must match those exposed by the
    /// deployed implementation. Catches the case where someone tweaks a
    /// contract constant without updating these tests — pinned digests
    /// would otherwise quietly diverge.
    function test_constants_matchContract() public {
        HypersnapBridge bridge = new HypersnapBridge();
        assertEq(bridge.DOMAIN_MERKLE_ROOT_UPDATE(), DOMAIN_MERKLE_ROOT_UPDATE);
        assertEq(bridge.DOMAIN_OWNER_UPDATE(),       DOMAIN_OWNER_UPDATE);
        assertEq(bridge.DOMAIN_OWNER_ACCEPTANCE(),   DOMAIN_OWNER_ACCEPTANCE);
        assertEq(bridge.DOMAIN_UPGRADE(),            DOMAIN_UPGRADE);
        assertEq(bridge.DOMAIN_UPGRADE_CANCEL(),     DOMAIN_UPGRADE_CANCEL);
        assertEq(bridge.DOMAIN_PAUSE(),              DOMAIN_PAUSE);
        assertEq(bridge.DOMAIN_RECOVER_ERC20(),      DOMAIN_RECOVER_ERC20);
        assertEq(bridge.DOMAIN_LOCK_LEAF(),          DOMAIN_LOCK_LEAF);
        assertEq(uint256(bridge.FAMILY_EVM()),       uint256(FAMILY_EVM));
    }
}
